--------------------------------------------------------
--  File created - Friday-January-20-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "APPVACATION"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table APP_USER
--------------------------------------------------------

  CREATE TABLE "APPVACATION"."APP_USER" 
   (	"USER_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(64 BYTE), 
	"PASSWORD" VARCHAR2(32 BYTE), 
	"ROLE" VARCHAR2(32 BYTE), 
	"DELETED" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "APPVACATION"."DEPARTMENT" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(64 BYTE), 
	"MANAGER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "APPVACATION"."EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(64 BYTE), 
	"LAST_NAME" VARCHAR2(64 BYTE), 
	"HIRE_DATE" DATE, 
	"MANAGER_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"PTO_AVAILABLE" NUMBER, 
	"PTO_USED" NUMBER, 
	"ACTIVE" NUMBER(*,0), 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUBLIC_HOLIDAY
--------------------------------------------------------

  CREATE TABLE "APPVACATION"."PUBLIC_HOLIDAY" 
   (	"DAY" DATE, 
	"AUTHOR_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUESTED_PTO
--------------------------------------------------------

  CREATE TABLE "APPVACATION"."REQUESTED_PTO" 
   (	"EMPLOYEE_ID" NUMBER, 
	"DAY" DATE, 
	"TYPE" VARCHAR2(64 BYTE), 
	"STATUS" VARCHAR2(64 BYTE), 
	"MANAGER_ID_APPROVAL" NUMBER, 
	"NOTES" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APPVACATION.APP_USER
SET DEFINE OFF;
Insert into APPVACATION.APP_USER (USER_ID,USERNAME,PASSWORD,ROLE,DELETED) values (14,'employee','fa5473530e4d1a5a1e1eb53d2fedb10c','EMPLOYEE',0);
Insert into APPVACATION.APP_USER (USER_ID,USERNAME,PASSWORD,ROLE,DELETED) values (6,'admin','21232f297a57a5a743894a0e4a801fc3','ADMIN',0);
REM INSERTING into APPVACATION.DEPARTMENT
SET DEFINE OFF;
Insert into APPVACATION.DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values (1,'Human Resources',5);
Insert into APPVACATION.DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values (2,'Accounting',13);
Insert into APPVACATION.DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values (3,'Engineering',17);
Insert into APPVACATION.DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values (4,'Executive Management',15);
Insert into APPVACATION.DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values (5,'Marketing',23);
Insert into APPVACATION.DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values (6,'Sales',23);
REM INSERTING into APPVACATION.EMPLOYEE
SET DEFINE OFF;
Insert into APPVACATION.EMPLOYEE (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,MANAGER_ID,DEPARTMENT_ID,PTO_AVAILABLE,PTO_USED,ACTIVE,USER_ID) values (13,'Employee1','Employee1',to_date('18-JAN-17','DD-MON-RR'),5,3,21,0,1,14);
Insert into APPVACATION.EMPLOYEE (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,MANAGER_ID,DEPARTMENT_ID,PTO_AVAILABLE,PTO_USED,ACTIVE,USER_ID) values (5,'Simona','Roboiu',to_date('05-FEB-17','DD-MON-RR'),5,1,21,0,1,6);
REM INSERTING into APPVACATION.PUBLIC_HOLIDAY
SET DEFINE OFF;
REM INSERTING into APPVACATION.REQUESTED_PTO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPVACATION"."EMPLOYEE_PK" ON "APPVACATION"."EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PUBLIC_HOLIDAY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPVACATION"."PUBLIC_HOLIDAY_PK" ON "APPVACATION"."PUBLIC_HOLIDAY" ("DAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPVACATION"."DEPARTMENT_PK" ON "APPVACATION"."DEPARTMENT" ("DEPARTMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REQUESTED_PTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPVACATION"."REQUESTED_PTO_PK" ON "APPVACATION"."REQUESTED_PTO" ("EMPLOYEE_ID", "DAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPVACATION"."UNIQUE_USERNAME" ON "APPVACATION"."APP_USER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_UK_NAME_UID
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPVACATION"."EMPLOYEE_UK_NAME_UID" ON "APPVACATION"."EMPLOYEE" ("FIRST_NAME", "LAST_NAME", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPVACATION"."USERS_PK" ON "APPVACATION"."APP_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PUBLIC_HOLIDAY
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."PUBLIC_HOLIDAY" ADD CONSTRAINT "PUBLIC_HOLIDAY_PK" PRIMARY KEY ("DAY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPVACATION"."PUBLIC_HOLIDAY" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."PUBLIC_HOLIDAY" MODIFY ("DAY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_USER
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."APP_USER" ADD CONSTRAINT "APP_USER_UK_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPVACATION"."APP_USER" ADD CONSTRAINT "APP_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPVACATION"."APP_USER" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."APP_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."APP_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."APP_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUESTED_PTO
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."REQUESTED_PTO" ADD CONSTRAINT "REQUESTED_PTO_PK" PRIMARY KEY ("EMPLOYEE_ID", "DAY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPVACATION"."REQUESTED_PTO" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."REQUESTED_PTO" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."REQUESTED_PTO" MODIFY ("DAY" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."REQUESTED_PTO" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_CHK1" CHECK (PTO_AVAILABLE >=0) ENABLE;
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("PTO_USED" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("PTO_AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("MANAGER_ID" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("HIRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_UK_NAME_UID" UNIQUE ("FIRST_NAME", "LAST_NAME", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPVACATION"."DEPARTMENT" MODIFY ("DEPARTMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPVACATION"."DEPARTMENT" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK1" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "APPVACATION"."EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_APPUSER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "APPVACATION"."APP_USER" ("USER_ID") ENABLE;
  ALTER TABLE "APPVACATION"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_MANAGER_FK" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "APPVACATION"."EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PUBLIC_HOLIDAY
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."PUBLIC_HOLIDAY" ADD CONSTRAINT "PUBLIC_HOLIDAY_FK1" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "APPVACATION"."EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUESTED_PTO
--------------------------------------------------------

  ALTER TABLE "APPVACATION"."REQUESTED_PTO" ADD CONSTRAINT "REQUESTED_PTO_MANAGER_FK" FOREIGN KEY ("MANAGER_ID_APPROVAL")
	  REFERENCES "APPVACATION"."EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
